#!/bin/bash

# Controller for developing and saving the site

# Builds the site, saves in docs/
# 

set -e
set -o pipefail

function usage() {
    echo "Usage: build|install"
    exit 1
}

action="$1"

if [[ "$action" == "" || "$action" == -* ]]
then
    usage
elif [[ "$action" == "build" ]]
then

    # Load up NVM
    export NVM_DIR="$HOME/.nvm" 
    if [[ ! -s $NVM_DIR/nvm.sh ]]
    then
        echo "ERROR: nvm is not installed; try ./run install"
        exit 1
    fi
        
    . "$NVM_DIR/nvm.sh"

    cd app 
    ./node_modules/.bin/vue-cli-service build --mode production --target app --dashboard
    cd ..
    rm -rf docs
    cp -r app/dist docs
    echo 'nickandluke.com' > docs/CNAME
elif [[ "$action" == "install" ]]
then
    
    export NVM_DIR="$HOME/.nvm"
    if [[ ! -s $NVM_DIR/nvm.sh ]]
    then
        echo "ERROR: This project requires NVM, see: https://github.com/nvm-sh/nvm"
        exit 1
    fi
else
    echo "Unrecognized action: $action"
    usage
fi
